site_name:        VarianceCovarianceEstimators.jl
repo_url:         https://github.com/JuliaEconometrics/VarianceCovarianceEstimators.jl
site_description: Variance Covariance Estimators Docs
site_author:      José Bayoán Santiago Calderón

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Model API: ModelAPI.md
  - Examples: Examples.md
  - References: References.md
